// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Counts
SEXP Counts(arma::colvec anno, arma::mat geno, const int min_mac);
RcppExport SEXP _AllelicSeries_Counts(SEXP annoSEXP, SEXP genoSEXP, SEXP min_macSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type anno(annoSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type geno(genoSEXP);
    Rcpp::traits::input_parameter< const int >::type min_mac(min_macSEXP);
    rcpp_result_gen = Rcpp::wrap(Counts(anno, geno, min_mac));
    return rcpp_result_gen;
END_RCPP
}
// OLS
SEXP OLS(const arma::colvec y, const arma::mat X);
RcppExport SEXP _AllelicSeries_OLS(SEXP ySEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(OLS(y, X));
    return rcpp_result_gen;
END_RCPP
}
// ResidVar
SEXP ResidVar(const arma::colvec y, const arma::mat X);
RcppExport SEXP _AllelicSeries_ResidVar(SEXP ySEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(ResidVar(y, X));
    return rcpp_result_gen;
END_RCPP
}
// Score
SEXP Score(const arma::colvec y, const arma::mat G, const arma::mat X, const double v);
RcppExport SEXP _AllelicSeries_Score(SEXP ySEXP, SEXP GSEXP, SEXP XSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type G(GSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(Score(y, G, X, v));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AllelicSeries_Counts", (DL_FUNC) &_AllelicSeries_Counts, 3},
    {"_AllelicSeries_OLS", (DL_FUNC) &_AllelicSeries_OLS, 2},
    {"_AllelicSeries_ResidVar", (DL_FUNC) &_AllelicSeries_ResidVar, 2},
    {"_AllelicSeries_Score", (DL_FUNC) &_AllelicSeries_Score, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_AllelicSeries(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
